### ISSUE TITLE
Add to F-Droid repository

### ISSUE THREAD

**Issue by lvella** [readbeyond/minstrel#3]
FDroid ( f-droid.org ) is a free software repository for Android. Please add it there for easy management and installation.

**Comment by pettarin** [comment]
Thank you for your comment/request.

At this stage, Menestrello/Minstrel is mostly abandonware, so no new features or extra management will be done.

I will consider uploading to FDroid the next time Google Play will require me to update my app for whatever reason (usually, for Cordova deprecation).

Leaving open for now.

**Comment by Ben-Waters** [comment]
Just as feedback, even in its 'abandonware' status it seems to be superior to the epub readers currently on f-droid. None of the available readers were able to open the epub file I had. Minstrel warned me I had to turn on the advanced feature for restricted pagination, and then it worked perfectly.

**Comment by readbeyond** [comment]
Thank you for the feedback. I am glad it works for you, but I really do not have time to maintain the app. Plus, I am not an app developer, I am more an R&D engineer with strong algorithmic focus.

Minstrel is free software (MIT license), so I am not against having it uploaded/included in F-Droid, but I will not do that myself, in order to avoid pressure to maintain it there.

**Comment by Rudloff** [comment]
Feel free to [open an RFP](https://gitlab.com/fdroid/rfp/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=) so other contributors can take care of packaging the app.

**Comment by IzzySoft** [comment]
@Rudloff one more? There already [is one](https://gitlab.com/fdroid/fdroiddata/merge_requests/2075), 2 years old…
